#server port 설정
server:
  port: 8081

#mariaDB 연동
spring:
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://localhost:3306/sagwan
    username: root
    password: maria
    
  mvc:
    #HttpHiddenMethod 사용 설정
    hiddenmethod:
      filter:
        enabled: true
  
  #view resolver 설정  
  thymeleaf:
    prefix: classpath:/templates/

#mybatis 환경설정    
mybatis:
  config-location: classpath:configuration.xml
  mapper-locations: classpath:mappers/*.xml
    